services:
  leetcode-db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
